name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:

jobs:
  check: # building smart contract, running lint and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Compile smart contract
        run: npm run compile

      - name: Run linting checks
        run: npm run lint

      - name: Run tests
        run: npm run test

  analysis: # static code analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v2

      - name: Run static analysis with slither
        id: slither
        uses: crytic/slither-action@v0.3.0
        continue-on-error: true
        with:
          sarif: results.sarif
          slither-args: --filter-paths node_modules # exclude other contracts

      - name: Upload SARIF output file # it should also add relevant comments on PR
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
